version: '3'

services:
  database:
    shm_size: "4gb"
    container_name: "oracle-container"
    image: container-registry.oracle.com/database/standard
    ports:
      - 1521:1521
      - 5500:5500
    environment:
      - ORACLE_SID=defects
      - ORACLE_BASE=/u01/app/oracle
      - ORACLE_HOME=/u01/app/oracle/product/12.1.0/dbhome_1
      - PATH=$PATH:/u01/app/oracle/product/12.1.0/dbhome_1/bin
      - LD_LIBRARY_PATH=/u01/app/oracle/product/12.1.0/dbhome_1/lib
    env_file:
      - .config/database.env
    volumes:
      - ./lab_01:/labs/lab_01
      - ./datasets:/datasets
      - ./scripts:/scripts
