CREATE USER alexey IDENTIFIED BY admin
DEFAULT TABLESPACE USERS QUOTA 100M ON USERS
/

GRANT CREATE SESSION TO alexey
/

GRANT CREATE TABLE TO alexey

GRANT CREATE PROCEDURE TO alexey
/

GRANT CREATE TRIGGER TO alexey
/

GRANT CREATE VIEW TO alexey
/

GRANT CREATE SEQUENCE TO alexey
/

GRANT ALTER ANY TABLE TO alexey
/
GRANT ALTER ANY PROCEDURE TO alexey
/
GRANT ALTER ANY TRIGGER TO alexey
/
GRANT ALTER PROFILE TO alexey
/

GRANT DELETE ANY TABLE TO alexey 
/
GRANT DROP ANY TABLE TO alexey
/
GRANT DROP ANY PROCEDURE TO alexey
/
GRANT DROP ANY TRIGGER TO alexey
/
GRANT DROP ANY VIEW TO alexey
/
GRANT DROP PROFILE TO alexey
/