CREATE DATABASE defects
  USER SYS IDENTIFIED BY -- Здесь пароль для SYS
  USER SYSTEM IDENTIFIED BY -- Здесь пароль для SYSTEM
  MAXLOGFILES 5
  MAXLOGHISTORY 10
  MAXDATAFILES 50
  CHARACTER SET US7ASCII
  NATIONAL CHARACTER SET AL16UTF16
  DEFAULT TABLESPACE USERS
  DEFAULT TEMPORARY TABLESPACE TEMPTS
  UNDO TABLESPACE UNDOTS;
