CREATE DATABASE defects
  USER SYS IDENTIFIED BY 061100
  USER SYSTEM IDENTIFIED BY 061100
  MAXLOGFILES 5
  MAXLOGHISTORY 10
  MAXDATAFILES 50
  CHARACTER SET US7ASCII
  NATIONAL CHARACTER SET AL16UTF16
  DEFAULT TABLESPACE USERS
  DEFAULT TEMPORARY TABLESPACE TEMPTS
  UNDO TABLESPACE UNDOTS;
