CREATE OR REPLACE PROCEDURE AuditWrapper(event_type IN VARCHAR2)
AS LANGUAGE JAVA
NAME 'CLRManager.AuditTrigger(java.lang.String)';
/

CREATE OR REPLACE TRIGGER ShutdownTriggerCLR
BEFORE SHUTDOWN ON DATABASE
BEGIN
    AuditWrapper('SHUTDOWN');
END;
/

CREATE OR REPLACE TRIGGER StartupTriggerCLR
AFTER STARTUP ON DATABASE
BEGIN
    AuditWrapper('STARTUP');
END;
/